  plugins:
  - jekyll-default-layout

title: Market Research Guide
description: A how-to-guide for technologies
theme: just-the-docs

url: https://MarketResearchGuide.github.io/Market-Research-Guide

  Template Repository: https://github.com/Market-Research-Guide/MarketResearchGuide
